import './globals.css'

export const metadata = {
  title: 'AUTOCODER',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body className='scrollbar-hide'>
        {children}
      </body>
    </html>
  )
}
